### ISSUE TITLE
UseMoonQueries (with multiple queries) considers only one query

### ISSUE THREAD

**Issue by hyacintheknobloch** [Decathlon/moon#7]
**Describe the bug**
I use the hook `withQueriesResults` and `resultsToProps` params in my component to get results of several queries but it loads query data one by one.

**To Reproduce**
1. Use withQueriesResults (with at least two queries that have already received their result)
2. Create resultsToProps method to give to withQueriesResults params
3. console.log queries results

**Expected behavior**
The console.log should display both queries results but it displays only one query result a time

**Screenshots**
Console.log display :
![test](https://user-images.githubusercontent.com/49550468/71522213-091fc700-28c4-11ea-8abb-60102b3e5d09.png)
Code : 
![image](https://user-images.githubusercontent.com/49550468/71522275-484e1800-28c4-11ea-935c-1b5b4414922d.png)

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Chrome
- Version: Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by amen-souissi** [comment]
:+1:
